# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

naive_cluster <- function(D, M, K, threshold = 1.0) {
    .Call('dfrtopics_naive_cluster', PACKAGE = 'dfrtopics', D, M, K, threshold)
}

calc_row_entropies <- function(m) {
    .Call('dfrtopics_calc_row_entropies', PACKAGE = 'dfrtopics', m)
}

#' Entropy of a vector
#'
#' This function computes the entropy of a vector, understood as a discrete
#' distribution over the index.
#'
#' @param x vector representing the distribution. Not checked to see whether it is properly normalized.
#'
#' @return \eqn{sum_i x_i \log x_i}, where the log is base 2 and the sum is taken only over non-zero elements of \eqn{x}.
#'
#' @export
entropy <- function(x) {
    .Call('dfrtopics_entropy', PACKAGE = 'dfrtopics', x)
}

#' Jensen-Shannon divergence between two vectors
#'
#' This function computes the Jensen-Shannon divergence between two vectors,
#' understood as distributions over the index.
#'
#' @param P,Q vectors representing the distributions. Must be of same length.
#'
#' @return \deqn{\sum_j \frac{1}{2}P(j) log\left(\frac{2P(j)}{P(j) +
#' Q(j)}\right) + \frac{1}{2}Q(j) log\left(\frac{2P(j)}{P(j) +
#' Q(j)}\right)}
#'
#' @seealso \code{\link{topic_divergences}}, \code{\link{row_dists}}
#'
#' @export
JS_divergence <- function(P, Q) {
    .Call('dfrtopics_JS_divergence', PACKAGE = 'dfrtopics', P, Q)
}

draw_multinom <- function(nn, probs) {
    .Call('dfrtopics_draw_multinom', PACKAGE = 'dfrtopics', nn, probs)
}

