# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Jensen-Shannon divergence between two vectors
#'
#' This function computes the Jensen-Shannon divergence between two vectors,
#' understood as distributions over the index.
#'
#' @param P,Q vectors representing the distributions. Must be of same length.
#'
#' @return \deqn{\sum_j \frac{1}{2}P(j) log\left(\frac{2P(j)}{P(j) +
#' Q(j)}\right) + \frac{1}{2}Q(j) log\left(\frac{2P(j)}{P(j) +
#' Q(j)}\right)}
#'
#' @seealso \code{\link{topic_divergences}}, \code{\link{row_dists}}
#'
#' @export
JS_divergence <- function(P, Q) {
    .Call('dfrtopics_JS_divergence', PACKAGE = 'dfrtopics', P, Q)
}

